.PHONY: clean All

All:
	@echo "----------Building project:[ qpbosolver - Debug ]----------"
	@"$(MAKE)" -f  "qpbosolver.mk"
clean:
	@echo "----------Cleaning project:[ qpbosolver - Debug ]----------"
	@"$(MAKE)" -f  "qpbosolver.mk" clean
