.PHONY: clean All

All:
	@echo "----------Building project:[ jnicpbo - Debug ]----------"
	@cd "jnicpbo" && "$(MAKE)" -f  "jnicpbo.mk"
clean:
	@echo "----------Cleaning project:[ jnicpbo - Debug ]----------"
	@cd "jnicpbo" && "$(MAKE)" -f  "jnicpbo.mk" clean
