/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qpbosolver_QPBOSolution */

#ifndef _Included_qpbosolver_QPBOSolution
#define _Included_qpbosolver_QPBOSolution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qpbosolver_QPBOSolution
 * Method:    create_qpbo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_qpbosolver_QPBOSolution_create_1qpbo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     qpbosolver_QPBOSolution
 * Method:    add_unary_energies
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_qpbosolver_QPBOSolution_add_1unary_1energies
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     qpbosolver_QPBOSolution
 * Method:    add_pairwise_energies
 * Signature: (IIDDDD)V
 */
JNIEXPORT void JNICALL Java_qpbosolver_QPBOSolution_add_1pairwise_1energies
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     qpbosolver_QPBOSolution
 * Method:    find_solution
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_qpbosolver_QPBOSolution_find_1solution
  (JNIEnv *, jobject);

/*
 * Class:     qpbosolver_QPBOSolution
 * Method:    get_flag
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qpbosolver_QPBOSolution_get_1flag
  (JNIEnv *, jobject, jint);

/*
 * Class:     qpbosolver_QPBOSolution
 * Method:    dispose_qpbo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_qpbosolver_QPBOSolution_dispose_1qpbo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
